name: Build

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  bethany-build-test:
    runs-on: ubuntu-latest
    env:
        CI: true
        RAILS_ENV: test
        RACK_ENV: test
        DISABLE_SPRING: 1
        LD_LIBRARY_PATH: /usr/local/lib
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_DB: dashboard_test
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_PASSWORD:
        ports:
          - "3306:3306"
    steps:
      - uses: actions/checkout@v2

      - name: Setup locals variables
        run: ./docker/setup_unit_tests_locals.sh

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Bundle install
        run: bundle install --with test

      - name: Start MySQL
        run: sudo /etc/init.d/mysql start

      - name: rake install
        run: bundle exec rake install
        env:
          DATABASE_PORT: 3306

      # Infer node version from .nvmrc, courtesy of https://github.com/actions/setup-node/issues/32#issuecomment-539794249
      - name: Read .nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm
      - name: Use Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

      - name: Build all
        run: rake build

