name: Run one test tests
on:
  workflow_dispatch:
jobs:
  run-ui-tests:
    runs-on: ubuntu-18.04
    services:
      mysql:
        image: mysql:5.7    
    env:        
      CI: true
      RAILS_ENV: test
      RACK_ENV: test
      DISABLE_SPRING: 1   
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_ACCESS_KEY:  ${{ secrets.SAUCE_ACCESS_KEY }}      
      LD_LIBRARY_PATH: "/usr/local/lib"
      LANG: C.UTF-8
    steps:   
      - name: Get actions code
        uses: actions/checkout@v3            
      - name: say-hello
        uses: ./.github/actions/start-server-job-actions  
      - name: Install mysql
        uses: ./.github/actions/install-mysql                    
      - name: Install test variables
        uses: ./.github/actions/install-test-variables            
      - name: Install Ruby
        uses: ./.github/actions/install-ruby
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get -y install libmagickwand-dev imagemagick
          curl -sSL -o /tmp/pdftk-java_3.0.9-1_all.deb https://mirrors.kernel.org/ubuntu/pool/universe/p/pdftk-java/pdftk-java_3.0.9-1_all.deb \
          && DEBIAN_FRONTEND=noninteractive dpkg -i /tmp/pdftk-java_3.0.9-1_all.deb || apt-get -fy install \
          && rm -rf /tmp/pdftk-java_3.0.9-1_all.deb
          apt-get update
          apt-get install -y libicu-dev enscript moreutils libmysqlclient-dev libsqlite3-dev
        
      - name: Install node
        uses: ./.github/actions/install-node        
      - name: Install rake dependencies 
        uses: ./.github/actions/install-rake-dependencies              
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3                    
      - name: Run tests
        run:  |
          brew reinstall imagemagick
          bundle exec rake test:changed:pegasus --trace          
        continue-on-error: true
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3                            

        
  
     
