name: Run one test tests
on:
  workflow_dispatch:
jobs:
  run-ui-tests:
    runs-on: ubuntu-latest
    env:        
      CI: true
      RAILS_ENV: test
      RACK_ENV: test
      DISABLE_SPRING: 1   
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_ACCESS_KEY:  ${{ secrets.SAUCE_ACCESS_KEY }}      
      LD_LIBRARY_PATH: "/usr/local/lib"
      LANG: C.UTF-8
    steps:   
      - name: Get actions code
        uses: actions/checkout@v3    
        
      - name: Rake run integration tests
        run:  |
          locale-gen
      - name: say-hello
        uses: ./.github/actions/start-server-job-actions  
      - name: Install mysql
        uses: ./.github/actions/install-mysql                    
      - name: Install test variables
        uses: ./.github/actions/install-test-variables            
      - name: Install Ruby
        uses: ./.github/actions/install-ruby
      - name: Install apt packages
        uses: ./.github/actions/install-apt-packages
      - name: Install node
        uses: ./.github/actions/install-node        
      - name: Install rake dependencies 
        uses: ./.github/actions/install-rake-dependencies
      - name: Install imagemagic
        run:  |  
          brew install imagemagick@6
          brew unlink imagemagick
          brew link imagemagick@6 --force
      - name: Rake run integration tests
        run:  |
          echo "testing failure"  
          brew install imagemagick@6
        continue-on-error: true               
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3                
  
     
